"""
Pydantic schemas for ImageAsset entities.

This module defines the request and response schemas for image asset operations
in the Menu Service (Module 0), handling GCS storage URLs for original and
automatically resized product images.
"""

from datetime import datetime
from typing import Optional, Dict
from enum import Enum

from pydantic import BaseModel, Field, ConfigDict, HttpUrl, field_validator


class ImageSize(str, Enum):
    """Enumeration of available image sizes."""

    THUMBNAIL = "thumbnail"
    SMALL = "small"
    MEDIUM = "medium"
    LARGE = "large"


class ImageAssetBase(BaseModel):
    """Base schema for ImageAsset with common fields."""

    product_id: int = Field(
        ...,
        description="Product identifier this image belongs to",
        examples=[1, 42]
    )
    gcs_url_original: str = Field(
        ...,
        min_length=1,
        description="Google Cloud Storage URL for the original uploaded image",
        examples=[
            "https://storage.googleapis.com/pos-images/products/original/hamburger-001.jpg",
            "gs://pos-images/products/original/pizza-margherita.png"
        ]
    )


class ImageAssetCreate(ImageAssetBase):
    """Schema for creating a new image asset."""
    pass


class ImageAssetUpdate(BaseModel):
    """Schema for updating an existing image asset."""

    product_id: Optional[int] = Field(
        None,
        description="Product identifier"
    )
    gcs_url_original: Optional[str] = Field(
        None,
        min_length=1,
        description="GCS URL for original image"
    )
    gcs_urls_resized: Optional[Dict[str, str]] = Field(
        None,
        description="GCS URLs for resized image variants"
    )


class ImageAssetInDB(ImageAssetBase):
    """Schema for image asset as stored in database."""

    model_config = ConfigDict(from_attributes=True)

    id: int = Field(
        ...,
        description="Unique image asset identifier",
        examples=[1, 42]
    )
    gcs_urls_resized: Optional[Dict[str, str]] = Field(
        None,
        description="GCS URLs for automatically resized image variants (generated by Cloud Function)",
        examples=[{
            "thumbnail": "https://storage.googleapis.com/pos-images/products/thumbnail/hamburger-001.jpg",
            "small": "https://storage.googleapis.com/pos-images/products/small/hamburger-001.jpg",
            "medium": "https://storage.googleapis.com/pos-images/products/medium/hamburger-001.jpg",
            "large": "https://storage.googleapis.com/pos-images/products/large/hamburger-001.jpg"
        }]
    )
    created_at: datetime = Field(
        ...,
        description="Timestamp when image asset was created"
    )

    @field_validator('gcs_urls_resized')
    @classmethod
    def validate_resized_urls(cls, v: Optional[Dict[str, str]]) -> Optional[Dict[str, str]]:
        """Validate that resized URLs follow the expected structure."""
        if v is None:
            return v

        valid_sizes = {size.value for size in ImageSize}
        for size, url in v.items():
            if size not in valid_sizes:
                raise ValueError(
                    f"Invalid image size '{size}'. Must be one of: {', '.join(valid_sizes)}"
                )
            if not url:
                raise ValueError(f"URL for size '{size}' cannot be empty")

        return v


class ImageAssetResponse(ImageAssetInDB):
    """Schema for image asset API responses."""
    pass


class ImageAssetListResponse(BaseModel):
    """Schema for paginated image asset list responses."""

    items: list[ImageAssetResponse] = Field(
        ...,
        description="List of image assets"
    )
    total: int = Field(
        ...,
        description="Total number of image assets",
        examples=[500]
    )
    page: int = Field(
        ...,
        ge=1,
        description="Current page number",
        examples=[1]
    )
    page_size: int = Field(
        ...,
        ge=1,
        le=100,
        description="Number of items per page",
        examples=[20]
    )


class SignedUploadUrl(BaseModel):
    """
    Schema for GCS signed URL used for direct image upload from frontend.

    The frontend will request a signed URL, upload the image directly to GCS,
    and then create an ImageAsset record with the uploaded URL.
    """

    upload_url: str = Field(
        ...,
        description="Time-limited signed URL for uploading image to GCS",
        examples=["https://storage.googleapis.com/pos-images/...?X-Goog-Signature=..."]
    )
    gcs_url: str = Field(
        ...,
        description="Final GCS URL where the image will be stored (to be used in ImageAssetCreate)",
        examples=["gs://pos-images/products/original/temp-uuid-123.jpg"]
    )
    expires_at: datetime = Field(
        ...,
        description="Timestamp when the signed URL expires"
    )
    max_file_size_mb: int = Field(
        10,
        ge=1,
        le=50,
        description="Maximum allowed file size in megabytes",
        examples=[10]
    )


class SignedUploadUrlRequest(BaseModel):
    """Schema for requesting a signed upload URL."""

    file_name: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Original file name (will be sanitized)",
        examples=["hamburger-photo.jpg", "product-image.png"]
    )
    content_type: str = Field(
        ...,
        pattern=r"^image/(jpeg|png|webp|gif)$",
        description="MIME type of the image",
        examples=["image/jpeg", "image/png", "image/webp"]
    )
    product_id: Optional[int] = Field(
        None,
        description="Product ID for organizing uploads (optional at upload time)",
        examples=[42]
    )


class ImageProcessingStatus(str, Enum):
    """Enumeration of image processing statuses."""

    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ImageProcessingEvent(BaseModel):
    """
    Schema for Cloud Function events triggered on image upload.

    This is used internally by the image resize Cloud Function to update
    the image_assets table with resized URLs.
    """

    image_asset_id: int = Field(
        ...,
        description="Image asset identifier",
        examples=[1]
    )
    status: ImageProcessingStatus = Field(
        ...,
        description="Processing status",
        examples=["COMPLETED", "FAILED"]
    )
    gcs_urls_resized: Optional[Dict[str, str]] = Field(
        None,
        description="GCS URLs for resized variants"
    )
    error_message: Optional[str] = Field(
        None,
        description="Error message if processing failed",
        examples=["Invalid image format", "Image too large"]
    )
